version: "3.7"
services:
  devops-utils:
    platform: linux/arm64/v8
    #image: cmdlabs/terraform-utils:11.0.3
    image: arthur210/terraform-runner:1.0.0
    env_file: .env
#    environment:
#      - AWS_SDK_LOAD_CONFIG=1
    entrypoint: ""
    volumes:
      - .:/work
      - ~/.aws:/root/.aws
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
    working_dir: /work

  #envvars:
  #  image: flemay/envvars:0.0.7
  #  env_file: .env
  #  working_dir: /work
  #  volumes:
  #    - .:/work
