instance_type = "t3.medium"
instance_name = ["arthur-test-master-node", "arthur-test-worker-node-01", "arthur-test-worker-node-02"]
owner = "arthur"
public_subnet_id = "subnet-06ea1f2042ed50645"
k8s_sg = "sg-0b9ffaf8d1e2afe89"
instance_count = 3
private_ips = ["10.0.0.2", "10.0.0.3"]
role_name = "ssm-arthur"
apply_script = true
script_path = "userdata/ansible/script.sh"
instance_profile_name = "test-profile-2"