apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    job: node-api
    app: api
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - name: name-of-service-port
    port: 80
    targetPort: 80
    nodePort: 30007
