name: Dockerfile package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  list-out:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup docker image
        run: ls -la ./container_images/
  
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build docker image
        run: |
          docker build ./container_images/terraform/. -t test-image
          docker image ps
          