# This is a basic workflow to help you get started with Actions

name: Arthur AWS Kubernetes Init/Plan/Apply

run-name: Run Terraform plan/apply on k8s resources


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ACCESS_KEY_ID: ASIA2QIXXJAZK3Z456EU
  SECRET_ACCESS_KEY: 0PExtXmoc9xSGzmcif3BqJ2iBpDTDONaJCrGNA6Z
  AWS_SESSION_TOKEN: IQoJb3JpZ2luX2VjEIv//////////wEaDmFwLXNvdXRoZWFzdC0yIkcwRQIgFBjbhIpJyOVrpGt05dgmll2JxJe0Xt60NKho+Sx871UCIQChWU/LPDNxxvaqTsiuJhbZbzb1k0VNCc/DARMLEInbSyqXAwjk//////////8BEAMaDDcyMjE0MTEzNjk0NiIMfyxxvgzJcSL0h3AoKusC+zGLM68/YpyBf3pGfN2CUt/mUzkr10dHfCIAY/ctFwGYT968Zzhh4cWE4TIRCV4W8k3tUPbJDuSf8weOghhiZmAc58isX39gcsahrrRmVubz3GjN1eDDe/U19PFyHxQ+chSNBZakYJjTjEIObNJ7CbUY+NSwt85kaRbkKZoT63Hx8xbPpulORs3Y7AMZ14DNABP78wS2d86kS2LBGbgQLyZqYkXekk7qXwoZB2CW9WrSWOf55n66f2N2qNFp/XtJF+cXZnAz/xIBzEUs079ulgw0vF2dHZYiG9IVnC3uoNW5dhQWjrmj8rmR3xmBRkO8L4lzymtEkw+U3xkoh42vF78K+jcBV+lpCHLnOic/Zw7GitvwdHBc132y4x8i/WUYPOpHr0TdL71RtfJ6FCynb9qF6fuccMGl8x4jOR5iumqhzmkyCLAk9xoOiW+5Hs/RlREYc5Nz6T7RnVJ8gKyogznmPukfemHEW4guMPaX1KQGOqYBcm7+mq+bNLMVkjeRwVKeG2cAlS2MfSpM0lwcVeiCdGJhWGQKnoWnGWCnI7pov/3kbN0va+6xnIks5RpfDyoYrNHoLbZ4YwYMTwl6hl8rVSdm0r/bDaciXqbwS1c660v2pXiOXBiwhQq/ja6Mc/6dXATg8y0BnsepJP9gxe9w+aQdzsVjaRHSaj0Weza9thALLBDPYWEUPwzg0jdKFGTS3FcnHInp9w==
  AWS_EC2_METADATA_DISABLED: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "setup"
  vpc-ec2-plan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TERRAFORM_ROOT_MODULE: environments/non-prod/ap-southeast-2/k8s

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Access AWS account
        # access key for devops aws
        run: |
          export AWS_ACCESS_KEY_ID=${{ env.ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ env.SECRET_ACCESS_KEY }}
          export AWS_SESSION_TOKEN=${{ env.AWS_SESSION_TOKEN }}
          aws sts get-caller-identity

      - name: Terraform Init
        run: |
          export AWS_ACCESS_KEY_ID=${{ env.ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ env.SECRET_ACCESS_KEY }}
          export AWS_SESSION_TOKEN=${{ env.AWS_SESSION_TOKEN }}          
          cd ${{ env.TERRAFORM_ROOT_MODULE }}
          terraform init
      
      - name: Terraform Plan
        run: |
          export AWS_ACCESS_KEY_ID=${{ env.ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ env.SECRET_ACCESS_KEY }}
          export AWS_SESSION_TOKEN=${{ env.AWS_SESSION_TOKEN }}
          cd ${{ env.TERRAFORM_ROOT_MODULE }}
          terraform plan -var-file="module.tfvars"
      
      - name: Terraform Show
        run: |
          export AWS_ACCESS_KEY_ID=${{ env.ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ env.SECRET_ACCESS_KEY }}
          export AWS_SESSION_TOKEN=${{ env.AWS_SESSION_TOKEN }}
          cd ${{ env.TERRAFORM_ROOT_MODULE }}
          terraform show

  vpc-ec2-apply:
    runs-on: ubuntu-latest
    environment: production
    needs: vpc-ec2-plan
    env:
      TERRAFORM_ROOT_MODULE: environments/non-prod/ap-southeast-2/k8s
    steps:
      - uses: actions/checkout@v3
      - name: Terraform Apply
        run: |
          export AWS_ACCESS_KEY_ID=${{ env.ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ env.SECRET_ACCESS_KEY }}
          export AWS_SESSION_TOKEN=${{ env.AWS_SESSION_TOKEN }}          
          cd ${{ env.TERRAFORM_ROOT_MODULE }}
          terraform init
          terraform plan -var-file="module.tfvars"
          terraform show
          terraform apply -var-file="module.tfvars" --auto-approve