# This is a basic workflow to help you get started with Actions

name: Login-to-AWS-account

run-name: Log in to the Devops AWS Account


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "setup"
  setup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Access AWS account
        # access key for devops aws
        env:
          ACCESS_KEY_ID: ASIA2QIXXJAZFDK42NQO
          SECRET_ACCESS_KEY: LtV5AqRPrdV9hhiAPMBnYj7YZZjKHfCfNr3/VCKk
          AWS_SESSION_TOKEN: IQoJb3JpZ2luX2VjEPz//////////wEaDmFwLXNvdXRoZWFzdC0yIkcwRQIhAKP+l1XvOm7rwdsGOPy9w2TMO81mQC7x9CalpP3yB+w9AiAKyArJmwv04OBF5xalQlEwSb5S3lDD347xENbmRSAoDCqOAwhVEAMaDDcyMjE0MTEzNjk0NiIMjcxoUW8HKhYMfVD8KusC7EgCapzZv9YeY9sarDmkt7vnq4s4djfCMuAFqu7dbnvZwhS0vdYLmewNl22ph36sF3aGACZFsCSk6Ncmzh7h/mGzfLxkqfU5PxYRl+u3qANQ8KPv3yJkO7XZI4Uq+x9tyaCSb2Jxvnj23DldC77WDbj3XkzzgRdBFWo+f36JlucR3yG9GCgLxu0KHE4r36WDcrGcsLes3Av8zsFAtapbejZoE/IVM52/PFQQAAK7cOqqmc507D7ZZQRsVJ6XILaZxbU++W/hFpZbO+0X0KgDZTqNWW3IoaW6u5OBu5m/bVhHrIIspjSb0qeD/a3i3TR7PlhPT4Rq0Xab+rQkvjXGm5Jd9ThtlogaeQzedvXZfMkUL2a3WsFPgPImzlsL70+Qb4xwPXo6eGGkjFPRJX6+fhaBw7EW8x2EZKWWNAptyzIWUhbE1gEChpbZ5Q6vKiZZcdl1UQPJTKQBm7yeZXesYNDPHnFAqwJOSGkOMMHotKQGOqYBq28XQib38UOdc7vjB091iRt+PNA/h69EkGtPnjxjWWuLBieWBlvapdrOaE1X9wbBloecklGEGVR6PQ+vL/ZBLbo0630i0w5DbtEC8l9QlahkVUTBvRrZqjzooVhtlT3QK68hc2+NeaD7qnfB2tBXxcBDCSVOo1RiKbavAZizF9C9pPa8g6h+QgmkB9zJdkD1m1GdCAAnoP+9c7ltcCk4RAYusbp54A==
          AWS_EC2_METADATA_DISABLED: true
        run: |
#          export AWS_ACCESS_KEY_ID=${{ env.ACCESS_KEY_ID }}
#          export AWS_SECRET_ACCESS_KEY="${{ env.SECRET_ACCESS_KEY }}
#          export AWS_SESSION_TOKEN=${{ env.AWS_SESSION_TOKEN }}
          export AWS_ACCESS_KEY_ID="ASIA2QIXXJAZFHCOLG6J"
          export AWS_SECRET_ACCESS_KEY="StcbD7QOL+Nm53zAkl2jQ/00ABdTlszz+Qs6k1cE"
          export AWS_SESSION_TOKEN="IQoJb3JpZ2luX2VjEP3//////////wEaDmFwLXNvdXRoZWFzdC0yIkcwRQIgJQ51f1YkJlrvmZpBBRabAYWUSwoX/A2ejjjFk8U4kvICIQCgJBFudfOlcwiC5cvqT/sKzbnc4GQj1MPBrq+mzCQS/iqOAwhWEAMaDDcyMjE0MTEzNjk0NiIMyuCj70wjDI0dBxL5KusC/YNiezAk5DrrpIQMi6J+03CotD5aocdIoycSy7zGX9ARCsrHqwtLG/bMhHWrGqg9+zmS4X0MT91mumIyr5JDXIOyDiDWbtSo1BmGQzF2A6vSvjWtJns/5Nrft7Rr6Vk1kV5rfTtu/TVh0UzvGvEqSuKHbzPwd1bMUFU6+8eCMWwPUuFLIzaFsea2ORNeaVEn/nKkoQ5ILBkF5Z6Uz7ynlcWD4VEDy+FNOT8/yTehNkeSznmc88/AADKCEethp1Tt+WiBmcXwZTR1dBdiIWVmFScQv7izApjflHYkAPZZNFsyP1MtauswKdKgDpeOzwaMYc0eNQQmpCrK3rDSR16KJyqUN+ayFc0rNn2AwoGMHcZiOLFFois8RhkbMykx0AZ2Pp0ALWU8wQIsBKXAeYRR6sGKZx24aeCFaEekk3R0fsJUoBn6ZKIUKTWYhmpl6ZhbjxVzr9C+AbzIo/ilPkPjCexFE1Y8Tay/esG9MMDttKQGOqYBxLBqYnUlT4WrbEmU1ZdpLAkaLiTlG/5O2gVmqNYA1Zr+H+7cA+Ci5RbYAon16fkQQrbier17oGGCyUEbVjMBO9sNYpWNOKThVf/mWFbUyfCGonlPezKNwIwOmO2IEFlUUtvvEDoY1/WGtX9GupuGPrLq7pxgulJ9EWguaS6pTIzG40KbXIOitGAwiYeRRGQIpPZHAleFJYh6O2asFsQYhGIY4+mvRw=="
          aws sts get-caller-identity

# AKIA3EQRIY757QAU2EG7
# oXwnZRG9c4k1vtwvOUyMwcbOnCJcHz9Qf+RYHNSK