# This is a basic workflow to help you get started with Actions

name: Login-to-AWS-account

run-name: Log in to the Devops AWS Account


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ACCESS_KEY_ID: ASIA2QIXXJAZIIFZPGEU
  SECRET_ACCESS_KEY: KGLbTECt5txV1wZp2qS4cDGCYUn2/bC1B/QZeRd0
  AWS_SESSION_TOKEN: IQoJb3JpZ2luX2VjENj//////////wEaDmFwLXNvdXRoZWFzdC0yIkcwRQIgYt7qwnSxkM6zaRzSBj8CXQwa83VlwA4BqoVY7VzKn2oCIQCsy9zgEg/J6Li80Zxl8FNnxnul8Ts4hYJPYMbsWDm9PSqOAwhBEAMaDDcyMjE0MTEzNjk0NiIM+ZEldSU3/xiIhQJgKusCoAF9D4m4pLUPz470cfuhNMpwCbFJYs0uAdIKtyluMYHJOSwaxyaqsMerxZJMhYkdYxxXcYfbiSXg4Z+5b3V7adA+Ae5+uxglU0mFIDOKkdG+RUgS9M2DaReXQ/78D9b4X0ScmxrUc2Hmg5s6gb9MLVtwUEKWeIui1bUIGKwNQI/WvwQbPkHcu8lCPqMZBlrtO1qz+b70c9iQcKMjjQjKwGcJ+uZzVNcyG8+yrb2pUugxM3phBDnAsJEXJO1RT0u4PIs/85vJk3JKIcy1A/sc3tuafkCqyGaEs+tsy8sM54rd3gzuzxa2Vff9mrEg3XPIXqiRBv3Kp2H262nyiXc87OgRvH+FvJpSd/lStuMjqk5e9tMLF5M5k1ntnO4BYNSoLEhVIYrSfBmGkHtckEiF93uxTwhyldmIiEFhDbzjetfrrkSE55Q5NfkSj/G2O/qBbrZErsdxPB+cDsS/1OTXaNCl5j5IxWbXVikNMJ2G5aQGOqYBTzhdmobt308mILk3HcBwpBSNGlWpeGr/QUH7/3rZD0PJgC4TXSeR4BUzgS1Lhh+2pgwuAJkteADf+ZEDtP4oH0Y/a5oOZhecSP9k8eDJARb/wYjB6642U3OhYfm95OuG6HR4VwzVPdGH0lTANNJFB3yGR5myxVpd8GNpPcSZ8/Q0e4Rg96JPq9MZ6toGOSnSbuo3psOXdVR+4xm/VHoasmLueyP64w==
  AWS_REGION: ap-southeast-2
  AWS_EC2_METADATA_DISABLED: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "setup"
  setup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git clone the repository
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::722141136946:role/arthur-OpenID-role-test
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}

      # Runs a set of commands using the runners shell
      - name: Access AWS account
        # access key for devops aws
        env:
          TERRAFORM_ROOT_MODULE: environments/non-prod/ap-southeast-2/s3
        run: |
          aws sts get-caller-identity
