# This is a basic workflow to help you get started with Actions

name: Arthur AWS Organization

run-name: Run Terraform plan/apply


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  organisation-init-plan-apply:
    runs-on: ubuntu-latest
    env:
      ACCESS_KEY_ID: AKIA3EQRIY757QAU2EG7
      SECRET_ACCESS_KEY: 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
      AWS_EC2_METADATA_DISABLED: true
      TERRAFORM_ROOT_MODULE: aws-organization
    steps:
      - name: Checkout the current repo
        uses: actions/checkout@v3

      - name: Access AWS Devops Account
        run: |
          aws configure set aws_access_key_id ${{ env.ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ env.SECRET_ACCESS_KEY }}
          aws sts get-caller-identity

      - name: Terraform Init
        run: |
          cd ${{ env.TERRAFORM_ROOT_MODULE }}
          terraform init
      
      - name: Terraform Plan
        run: |
          cd ${{ env.TERRAFORM_ROOT_MODULE }}
          terraform plan -out tf.plan

      - name: Terraform apply
        run: |
          cd ${{ env.TERRAFORM_ROOT_MODULE }}
          terraform apply -input=false tf.plan