# This is a basic workflow to help you get started with Actions

name: Arthur AWS Resource Init/Plan/Apply

run-name: Run Terraform plan/apply on AWS resources


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ACCESS_KEY_ID: ASIA2QIXXJAZBAZTKGMH
  SECRET_ACCESS_KEY: iDR0HCbN59kfCeC+GwEebP1+UFJ2tP1oTrWoxjGj
  AWS_SESSION_TOKEN: IQoJb3JpZ2luX2VjEIz//////////wEaDmFwLXNvdXRoZWFzdC0yIkcwRQIgfW/WPwrrH5Zsqp0OQTIVoCEkiVUJXf9F1RnrdSh4yY0CIQDRg2TIyEkCiHCb+dAz/jp824pQF56f7ZVNPeoDsCou9yqOAwhVEAMaDDcyMjE0MTEzNjk0NiIMNXM2xuVH1lbIPfarKusCdOb+Ge001Bgup7IhBtC/aXGQguCxxjJe1YjLF0GpXGCLaRwwMPCVxTRvPHhIAwR+ZwmAH3x3H8njudlK4vrlHYOJvx3/8ILD4CGK+rvJLnHFCjilxtgCakaKOjgPuxq5I01ELZ8/mJ3lx34dGvFIwNvRtpvraz10svF2vT+AyQnQG4EVCGcizkl0rNesNZmywonl1KUcA+VT9hcSlaxfmRD1+GAeLtB1ONBnvHz3AF8yeOofekgIzqxvL4dtMeABKJjCcCbKlUDd/wIXEnQTMIs8xhjpV82XDPuONyhrfzk2kKbnpZdor2n/W/nL1n8zkkHT+S9rGOpAObtO7RiniCzA/Ws1RNSe4KMqSVko3bnzWSa9i4MaXHCiovMJZWINLNdsvxCyzXUV2qOJBI6rxV0TkwxtawcEQ80iUCGPzQ0LsUvjfpqh374Wqz8bCh+GzXLWmp7wxImy3p2IwokkvSB/YyrNDPw20kJJMLrspacGOqYBjYokV6bR/h9+sOHrF/WXsAv/zbGKX42HJW82CHZxjmaB3DVoCDLfXEFbQuaSlLEKYRoB4DmJ20d0D/zCvEWRRSlRo099Q0+bUYgz2MRJn6xiB8L5vQcU3fSoWzrh0ZNKHhLSLueC9/nZmiLtUzZTdfZhKq80fuIJNGuqNs5DE1bcjGPpbtHNS8TyYBdMDwYcwvraYvhRteoxNruGIhiVisX9RyQwFQ==
  AWS_EC2_METADATA_DISABLED: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "setup"
  vpc-plan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
#    runs-on: ['self-hosted', 'linux', 'x64']
    env:
      TERRAFORM_ROOT_MODULE: accounts/environments/non-prod/vpc

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Access AWS account
        # Assume role from 1 account to do stuff in other accounts
        run: |
          make sts

      - name: Terraform Init
        run: |        
          make init
      
      - name: Terraform Plan
        run: |
          make plan
      
      - name: Terraform Show
        run: |
          make show

  vpc-apply:
    runs-on: ubuntu-latest
#    runs-on: ['self-hosted', 'linux', 'x64']
    environment: production
    needs: vpc-plan
    env:
      TERRAFORM_ROOT_MODULE: accounts/environments/non-prod/vpc
    steps:
      - uses: actions/checkout@v3
      - name: Terraform Apply
        run: |      
          make apply
