# This is a basic workflow to help you get started with Actions

name: Arthur AWS Resource Init/Plan/Apply

run-name: Run Terraform plan/apply on AWS resources


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ACCESS_KEY_ID: ASIA2QIXXJAZOXUIHHP3
  SECRET_ACCESS_KEY: JgcLGytL3y+Sq9MlmIerU327XtjSI5+DbJIv54gF
  AWS_SESSION_TOKEN: IQoJb3JpZ2luX2VjEGIaDmFwLXNvdXRoZWFzdC0yIkYwRAIgQyIdjABcnoSByU5MEiWpBKeWFgCcAmtC0Y3o6q5CvvwCICwYhsQ0kIfYeWNYTRSLMIt66XHWDpFYoegreCCan5TiKo4DCCsQAxoMNzIyMTQxMTM2OTQ2IgwDp1QivqrePzdHADEq6wJeJnt4CL2A9C2NHVefWXH6z0jnKNNSiSCoL/iluB2+yAZEU5ao5VkJDF352NPd35RrUC2WlVvY+GKgQpk22V1DFRS7O3FYgzPbuT7nDTsJrayhQZ8JF6wHQrOQfwJBzA5CwNLwTF7YkoHVbZXKS/soXZ+AtclOnlqjb6V3KC9AFpOhMCPISCaCIPXRuZ3ifRe6wZYdFULVMa3/ZTGL7OGZ6dEydxGXYFiKAmE4snhTanXErL4K/G3FrhzJM8EeKuaN1SgvVLFmtddnbfMjdIpjplsW9yTut21LYbFCwjU24piCcauXySvb+rIdIYqG8OBnmM7p0QNRlCOVVry+krDfKheDMFBCDdlrbzy7TT+IYhMqAXNFhLWfQWF1RcsTfeBdjsKpdK2PmMnY1vmp42bm4ySgL0+QoQ+vtB09l/khFIMqfyrcFn+J6qZ/x2brM+Yo5XajKFbkWaYaIJWzYJs9cCWee4LsWEMADxww/sycpwY6pwF60bPm5msiMbAJy2tN1DSt/kbCHGieGdd2xHmwuYXg1MrKN7yhau/gaXo3lBVfWh5uxEUNVDBQVhPBVJA4us+x6JUTp6IWM2PMg1MZFyDtXqPLLxxZDJUAf+X7uZU1J1pNXpw/CHdO5XlGT9es0M28XwcL2yjQ6QjDAHKGQM2Idcmgh9eVM/0TJ+iAi/f0YkUkmYfOWVE9MrOdK1h9/jxLsyimRvcDtw==
  AWS_EC2_METADATA_DISABLED: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "setup"
  vpc-plan:
    # The type of runner that the job will run on
#    runs-on: ubuntu-latest
    runs-on: ['self-hosted', 'linux', 'x64']
    env:
      TERRAFORM_ROOT_MODULE: environments/non-prod/ap-southeast-2/vpc

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Access AWS account
        # Assume role from 1 account to do stuff in other accounts
        run: |
          make sts

      - name: Terraform Init
        run: |        
          make init
      
      - name: Terraform Plan
        run: |
          make plan
      
      - name: Terraform Show
        run: |
          make show

  vpc-apply:
    runs-on: ['self-hosted', 'linux', 'x64']
    environment: production
    needs: vpc-plan
    env:
      TERRAFORM_ROOT_MODULE: environments/non-prod/ap-southeast-2/vpc
    steps:
      - uses: actions/checkout@v3
      - name: Terraform Apply
        run: |      
          make apply